const Interface = {
  CALCULATOR_MOBILE_USE_CONTINUOUS_SCROLLING: true,
  CALCULATOR_NEW_SHOW_SYMBOL_INPUT: false,
  REHYDRATE_V2_CALCS: true,
  ALLOW_PUBLIC_PORTFOLIO_ACCESS: false,
  ENABLE_LOCAL_SAVED_CALCS: true,
  ENABLE_ANONYMOUS_AUTH: true,
  ANONYMOUS_AUTH_WAIT_FOR_CALC: true,
};

export default Interface;
