import CONTENT_PATHS from './CONTENT_PATHS';

const CMS_CONTENT_MAP = {
  [CONTENT_PATHS.HELP_STOCK_LEG]:
    'd/e/2PACX-1vR69HDMvpJGpb-oX0S_BTLqJHzg_mS2I4BCTy6qZrKshBMhDHG9BcZfMoJGmIHnK66_O80nA7BzGKiC',
  [CONTENT_PATHS.HELP_ESTIMATE_SUMMARY]:
    'd/e/2PACX-1vTtWgV9CDT70O54MMBrEpv3EFJAwXawMjF3vThwHmK047hNRi4-g1BC3DIE8qmHQ1ei4AwwjpNJN0R6',
  [CONTENT_PATHS.ABOUT_WHATS_NEW]:
    'd/e/2PACX-1vRhl-zP-A3bKsIrdXEiFetMQPedIntOIJopye8h03pURRcQ7dXLKoZUJ94MTBCS6BtHFDqd52Ws8SP7',
};

export default CMS_CONTENT_MAP;
