import MESSAGES from './MESSAGES';

export default {
  [MESSAGES.EXCHANGE_NOT_FOUND]: 404,
  [MESSAGES.OPTIONS_NOT_FOUND]: 404,
  [MESSAGES.CALCULATION_ERROR]: 400,
  [MESSAGES.CALCULATION_INVALID_STRATEGY]: 412,
} as Record<string, number>;
